[package]
name = "pps-server"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["macros", "tracing"] }
serde = "1.0.115"
serde_json = "1.0.57"
anyhow = "1.0.32"
toml = "0.5.6"
thiserror = "1.0.20"
async-trait = "0.1.38"
getrandom = "0.1.14"
glob = "0.3.0"
pom = { path = "../../pom" }
libc = "0.2.76"
roxmltree = "0.13.0"
serde_yaml = "0.8.13"
pest = "2.1.3"
pest_derive = "2.1.0"
formatf = { git = "https://github.com/mikailbag/formatf" }
svaluer = { path = "../../svaluer" }
hex = "0.4.2"
pps-api = { path = "../api" }
hyper = "0.13.7"
tracing = "0.1.19"
tracing-futures = { version = "0.2.4", features = ["futures-03"] }
either = "1.6.0"
rpc = { git = "https://github.com/jjs-dev/commons" }
futures-util = "0.3.5"
