[package]
name = "ppc"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = """
PPC is tool for prepararing problems and contests
"""

[dependencies]
structopt = "0.3.8"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.6"
glob = "0.3.0"
libc = "0.2.66"
pom = {path = "../pom"}
serde_json = "1.0.44"
getrandom = "0.1.14"
hex = "0.4.0"
formatf = { git = "https://github.com/mikailbag/formatf" }
roxmltree = "0.9.0"
anyhow = "1.0.26"
svaluer = {path = "../svaluer"}
thiserror = "1.0.11"
pest = "2.1.3"
pest_derive = "2.1.0"
serde_yaml = "0.8.11"
entity = {path = "../entity"}
tokio = {version = "0.2.16", features = ["process", "macros", "rt-threaded", "fs"]}
async-trait = "0.1.30"
