[package]
name = "ppc"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = """
PPC is tool for prepararing problems and contests
"""

[dependencies]
structopt = "0.3.13"
serde = { version = "1.0.106", features = ["derive"] }
toml = "0.5.6"
glob = "0.3.0"
libc = "0.2.68"
pom = {path = "../pom"}
serde_json = "1.0.51"
getrandom = "0.1.14"
hex = "0.4.2"
formatf = { git = "https://github.com/mikailbag/formatf" }
roxmltree = "0.10.1"
anyhow = "1.0.28"
svaluer = {path = "../svaluer"}
thiserror = "1.0.15"
pest = "2.1.3"
pest_derive = "2.1.0"
serde_yaml = "0.8.11"
entity = {path = "../entity"}
tokio = { version = "0.2.18", features = ["process", "macros", "rt-threaded", "fs"] }
async-trait = "0.1.30"
