[profile.release]
lto = true

[profile.dev]
debug = 1

[workspace]
# TODO: add other as they are fixed
members=["src/devtool", "src/gen-api-client", "src/cli", "src/client",
  "src/problem-loader",
  "src/dist-files-generator", "src/dist-builder", "src/ppc"]
