[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
entity = {path ="../entity"}
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
db = {path = "../db"}
dotenv = "0.15.0"
aho-corasick = "0.7.10"
invoker-api = {path = "../invoker-api"}
pom = {path = "../pom"}
libc = "0.2.68"
nix = "0.17.0"
strum = "0.18.0"
strum_macros = "0.18.0"
chrono = "0.4.11"
tempfile = "3.1.0"
fs_extra = "1.1.0"
base64 = "0.12.0"
bitflags = "1.2.1"
util = {path = "../util"}
anyhow = "1.0.28"
thiserror = "1.0.15"
uuid = { version = "0.8.1", features = ["v5"] }
problem-loader = {path = "../problem-loader"}
tokio = { version = "0.2.21", features = ["rt-core", "process", "io-std", "macros", "fs", "sync"] }
log = "0.4.8"
async-trait = "0.1.30"
num_cpus = "1.12.0"
serde_yaml = "0.8.11"
openssl = "0.10.29"
actix-web = {version = "2.0.0", features = ["openssl"], default-features = false}
actix-rt = {version = "1.1.0", default-features = false}
once_cell = "1.3.1"
