
[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {git = "https://github.com/jjs-dev/minion"}
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
dotenv = "0.15.0"
aho-corasick = "0.7.13"
invoker-api = {path = "../invoker-api"}
pom = {path = "../pom"}
libc = "0.2.76"
nix = "0.18.0"
strum = "0.19.2"
strum_macros = "0.19.2"
chrono = "0.4.15"
tempfile = "3.1.0"
fs_extra = "1.2.0"
base64 = "0.12.3"
bitflags = "1.2.1"
util = {path = "../util"}
anyhow = "1.0.32"
thiserror = "1.0.20"
uuid = { version = "0.8.1", features = ["v5"] }
problem-loader = {path = "../problem-loader"}
tokio = { version = "0.2.22", features = ["rt-core", "process", "io-std", "macros", "fs", "sync"] }
async-trait = "0.1.40"
num_cpus = "1.13.0"
serde_yaml = "0.8.13"
openssl = "0.10.30"
actix-web = { version = "2.0.0", features = ["openssl"], default-features = false }
actix-rt = { version = "1.1.1", default-features = false }
once_cell = "1.4.1"
client = {path = "../client"}
kube = { version = "0.40.0", optional = true }
k8s-openapi = { version = "0.9.0", optional = true, features = ["v1_17"], default-features = false }
puller = { git = "https://github.com/jjs-dev/commons" }
tracing = "0.1.19"
tracing-futures = "0.2.4"
async-mpmc = { git = "https://github.com/jjs-dev/commons" }
multiwake = { git = "https://github.com/jjs-dev/commons" }
dkregistry = { git = "https://github.com/mikailbag/dkregistry-rs", branch = "all" }

[features]
k8s = ["kube", "k8s-openapi"]
