[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
cfg = {path ="../cfg"}
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
db = {path = "../db"}
dotenv = "0.15.0"
ctrlc = { version = "3.1.3", features = ["termination"] }
aho-corasick = "0.7.6"
invoker-api = {path = "../invoker-api"}
cfg-if = "0.1.10"
pom = {path = "../pom"}
libc = "0.2.66"
nix = "0.16.1"
memchr = "2.2.1"
strum = "0.17.1"
strum_macros = "0.17.1"
chrono = "0.4.10"
color-backtrace = { version = "0.3.0", optional = true }
tempfile = "3.1.0"
fs_extra = "1.1.0"
atty = "0.2.13"
base64 = "0.11.0"
bitflags = "1.2.1"
util = {path = "../util"}
slog-scope = "4.3.0"
anyhow = "1.0.26"
thiserror = "1.0.9"
reqwest = "0.10.0"

[features]
beautiful_backtrace = ["color-backtrace"]
default = ["beautiful_backtrace"]
