[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
entity = {path ="../entity"}
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
db = {path = "../db"}
dotenv = "0.15.0"
aho-corasick = "0.7.6"
invoker-api = {path = "../invoker-api"}
pom = {path = "../pom"}
libc = "0.2.66"
nix = "0.16.1"
strum = "0.17.1"
strum_macros = "0.17.1"
chrono = "0.4.10"
tempfile = "3.1.0"
fs_extra = "1.1.0"
base64 = "0.11.0"
bitflags = "1.2.1"
util = {path = "../util"}
anyhow = "1.0.26"
thiserror = "1.0.10"
uuid = {version = "0.7.4", features = ["v5"]}
problem-loader = {path = "../problem-loader"}
tokio = {version = "0.2.13", features = ["rt-core", "process", "io-std", "macros", "fs"]}
log = "0.4.8"
async-trait = "0.1.27"
num_cpus = "1.12.0"
serde_yaml = "0.8.11"
openssl = "0.10.29"
actix-web = {version = "2.0.0", features = ["openssl"]}
actix-rt = "1.1.0"
