[package]
name = "invoker"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
judging-apis = { path = "../judging-apis" }
rpc = { git = "https://github.com/jjs-dev/commons" }
minion = {git = "https://github.com/jjs-dev/minion"}
hyper = "0.13.8"
tokio = { version = "0.2.22", features = ["macros", "io-std"] }
anyhow = "1.0.34"
futures-util = "0.3.7"
tracing = "0.1.21"
nix = "0.19.0"
once_cell = "1.4.1"
serde = { version = "1.0.117", features = ["derive"] }
