[package]
name = "util"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libsystemd = "0.1.0"
log = "0.4.8"
atty = "0.2.14"
url = "2.1.1"
anyhow = "1.0.28"
reqwest = { version = "0.10.4", features = ["blocking"] }
entity = {path = "../entity"}
problem-loader = {path = "../problem-loader"}
env_logger = "0.7.1"
