[package]
name = "util"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
anyhow = "1.0.33"
tracing-subscriber = "0.2.14"
tracing = "0.1.21"
