[package]
name = "svaluer"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
invoker-api = {path = "../invoker-api"}
anyhow = "1.0.32"
pom  = {path = "../pom"}
crossbeam-channel = "0.4.3"
serde_json = "1.0.57"
serde = "1.0.115"
util = {path = "../util"}
serde_yaml = "0.8.13"
log = "0.4.11"
either = "1.6.0"

[dev-dependencies]
simple_logger = "1.9.0"
