[package]
name = "svaluer"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
invoker-api = {path = "../invoker-api"}
anyhow = "1.0.33"
pom  = {path = "../pom"}
crossbeam-channel = "0.5.0"
serde_json = "1.0.59"
serde = "1.0.117"
util = {path = "../util"}
serde_yaml = "0.8.14"
log = "0.4.11"
either = "1.6.1"

[dev-dependencies]
simple_logger = "1.11.0"
