[package]
name = "cli"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = "JJS CLI client"

[dependencies]
util = {path = "../util"}
client = {path = "../client"}
structopt = "0.3.13"
base64 = "0.12.0"
serde_json = "1.0.51"
serde = "1.0.106"
futures = { version = "0.3.4", features = ["compat"] }
tokio = { version = "0.2.18", features = ["macros", "rt-core"] }
log = "0.4.8"
