[package]
name = "cli"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = "JJS CLI client"

[dependencies]
util = {path = "../util"}
client = {path = "../client"}
structopt = "0.3.8"
base64 = "0.11.0"
serde_json = "1.0.44"
serde = "1.0.104"
futures = {version = "0.3.4", features = ["compat"]}
tokio = {version = "0.2.13", features = ["macros", "rt-core"]}
log = "0.4.8"
