[package]
name = "invoker-api"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"
bitflags = "1.2.1"
pom = {path = "../pom"}
uuid = { version = "0.8.1", features = ["serde"] }
