[package]
name = "setup"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"
description = """
Simple utility to setup JJS on current host
"""

[dependencies]
backtrace = "0.3.46"
fs_extra = "1.1.0"
structopt = "0.3.13"
util = {path = "../util"}
log = "0.4.8"
url = "2.1.1"
anyhow = "1.0.28"
tokio-postgres = "0.5.3"
tokio = { version = "0.2.18", features = ["macros", "fs", "process", "io-std"] }
thiserror = "1.0.15"
async-trait = "0.1.30"
serde = { version = "1.0.106", features = ["derive"] }
serde_yaml = "0.8.11"
serde_json = "1.0.51"
toml = "0.5.6"
futures = "0.3.4"
flate2 = {version = "1.0.14", features = ["tokio"]}
tar = "0.4.26"
