[package]
name = "pps-api"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
reqwest = "0.10.8"
anyhow = "1.0.32"
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["sync"] }
tracing = "0.1.19"
rpc = { git = "https://github.com/jjs-dev/commons" }
