[package]
name = "problem-loader"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"


[dependencies]
pom = {path = "../pom"}
anyhow = "1.0.28"
serde_json = "1.0.51"
