[package]
name = "problem-loader"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"


[dependencies]
pom = {path = "../pom"}
anyhow = "1.0.33"
serde_json = "1.0.59"
async-trait = "0.1.41"
tokio = { version = "0.2.22", features = ["fs"] }
fs_extra = "1.2.0"
mongodb = "1.1.1"
url = "2.1.1"
bson = "1.1.0"
flate2 = "1.0.18"
tar = "0.4.30"
serde = "1.0.117"
tracing = "0.1.21"
tracing-futures = "0.2.4"
