
[package]
name = "judge"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {git = "https://github.com/jjs-dev/minion"}
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
dotenv = "0.15.0"
aho-corasick = "0.7.14"
judging-apis = {path = "../judging-apis"}
pom = {path = "../pom"}
libc = "0.2.80"
nix = "0.19.0"
strum = "0.19.5"
strum_macros = "0.19.4"
chrono = "0.4.19"
tempfile = "3.1.0"
fs_extra = "1.2.0"
base64 = "0.13.0"
bitflags = "1.2.1"
util = {path = "../util"}
anyhow = "1.0.33"
thiserror = "1.0.21"
uuid = { version = "0.8.1", features = ["v5"] }
problem-loader = {path = "../problem-loader"}
tokio = { version = "0.2.22", features = ["rt-core", "process", "io-std", "macros", "fs", "sync"] }
async-trait = "0.1.41"
num_cpus = "1.13.0"
serde_yaml = "0.8.14"
openssl = "0.10.30"
actix-web = { version = "3.2.0", features = ["openssl"], default-features = false }
actix-rt = { version = "1.1.1", default-features = false }
once_cell = "1.4.1"
client = {path = "../client"}
kube = { version = "0.43.0", optional = true }
k8s-openapi = { version = "0.9.0", optional = true, features = ["v1_17"], default-features = false }
puller = { git = "https://github.com/jjs-dev/commons" }
tracing = "0.1.21"
tracing-futures = "0.2.4"
dkregistry = { git = "https://github.com/mikailbag/dkregistry-rs", branch = "all" }
rpc = { git = "https://github.com/jjs-dev/commons", branch = "rpc-box-engine" }
tower-service = "0.3.0"
hyper = "0.13.7"
futures-util = "0.3.5"
event-listener = "2.4.0"
async-channel = "1.4.2"
parking_lot = "0.11.0"

[features]
k8s = ["kube", "k8s-openapi"]
