[package]
name = "userlist"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
client = {path = "../client"}
futures = { version = "0.3.4", features = ["compat"] }
structopt = "0.3.13"
base64 = "0.12.0"
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1.0.106", features = ["derive"] }
tokio = { version = "0.2.18", features = ["macros", "rt-core"] }
thiserror = "1.0.15"
