[package]
name = "dist-builder"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.17"
serde_json = "1.0.57"
serde = { version = "1.0.115", features = ["derive"] }
util = {path = "../util"}
log = "0.4.11"
anyhow = "1.0.32"
