[package]
name = "dist-builder"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
serde_json = "1.0.51"
serde = { version = "1.0.106", features = ["derive"] }
util = {path = "../util"}
log = "0.4.8"
anyhow = "1.0.28"
