---
- hosts: all
  vars:
    setup_profile: "{{ lookup('template', './profile-template.yaml.j2') }}"
  vars_prompt:
    - name: pkg_path
      prompt: "Where on local host jjs package is located?"
      private: false
      default: "/opt/jjs/pkg/jjs.deb"
    - name: db_addr
      prompt: "Database address (must include port; can be urlencoded unix socket path instead)"
      private: false
      default: "%2Fvar%2Frun%2Fpostgresql"
  roles:
    - db
    - role: jjs_common
  tasks:
    - name: Install required APT packages
      apt:
        name: ["g++"]
        update_cache: true
    - name: Setup JJS
      command:
        # Note that "-" is passed as profile path. It tells `jjs-setup` to read profile from stdin.
        cmd: jjs-setup - upgrade
        stdin: "{{ setup_profile }}"
      become: true
      become_user: jjs
    - name: Reload SystemD
      systemd:
        daemon_reload: true
    - name: Start JJS invoker
      service:
        name: jjs-invoker
        state: restarted
    - name: Start JJS apiserver
      service:
        name: jjs-apiserver
        state: restarted
