[package]
name = "minion"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
libc= "0.2.66"
errno= "0.2.4"
rand = "0.7.3"
cfg-if = "0.1.10"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
tiny-nix-ipc = { git = "https://github.com/myfreeweb/tiny-nix-ipc", features = ["ser_json", "zero_copy"] }
procfs = "0.7.7"
nix = "0.16.1"
snafu = "0.6.2"
backtrace = "0.3.41"
