apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoker
  labels:
    app: invoker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoker
  template:
    metadata:
      labels:
        app: invoker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: invoker
          env: []
          image: "{{ .Values.image.repositoryPrefix }}invoker:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          securityContext: 
            privileged: true
          ports:
            - name: http
              containerPort: 1789
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
