#{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: builtin-apiserver
spec:
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: builtin-judge
spec:
  podSelector:
    matchLabels:
      app: judge
  policyTypes:
  - Ingress
  ingress: []

#{{ if .Values.toolchains }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: builtin-init-deny-ingress
spec:
  podSelector:
    matchLabels:
      app: init
  policyTypes:
  - Ingress
  ingress: []

#{{- end }}

#{{- end }}
