[package]
name = "minion-cli"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
structopt = "0.3.7"
chrono = { version = "0.4.10", features = ["serde"] }
libc = "0.2.66"
