[package]
name = "minion-cli"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
minion = {path = "../minion"}
structopt = "0.3.6"
human-panic = { version = "1.0.1", optional = true }
cfg-if = "0.1.10"
chrono = { version = "0.4.10", features = ["serde"] }

[features]
human_panic = ["human-panic"]
