[package]
name = "dist-files-generator"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
serde = "1.0.117"
util = {path = "../util"}
anyhow = "1.0.33"
fs_extra = "1.2.0"
