[package]
name = "client"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
openapi = {path = "../gen-api-client"}
hyper = "0.13"
tokio = "0.2.13"
serde_json = "1.0.48"
