[package]
name = "judging-apis"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
strum = "0.19.5"
strum_macros = "0.19.4"
bitflags = "1.2.1"
pom = {path = "../pom"}
uuid = { version = "0.8.1", features = ["serde"] }
rpc = { git = "https://github.com/jjs-dev/commons" }
hyper = "0.13.7"
anyhow = "1.0.32"
base64 = "0.12.3"
futures-util = "0.3.5"
