[package]
name = "e2e"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
frontend-engine = {path = "../frontend-engine"}

[dev-dependencies]
reqwest = { version = "0.10.1", features = ["blocking"] }
serde_json = "1.0.45"
base64 = "0.11.0"
