---
name: deploy
"on":
  push:
    branches:
      - master
      - fixup-deploy
env:
  CI: 1
  RUST_BACKTRACE: full
  RUSTC_BOOTSTRAP: 1
jobs:
  docker:
    name: docker
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: "clippy,rustfmt"
          override: true
      - name: Install system dependencies
        run: sudo apt-get install -y libssl-dev cmake
      - name: Build images
        run: "mkdir artifacts\nDOCKER_OPT=\"--enable-docker --docker-tag=% --docker-tags-log=/tmp/taglog.txt --with-docker=docker\"\ncargo jjs-build --out artifacts $DOCKER_OPT --enable=apiserver --enable=invoker\n"
      - name: Upload images
        run: "docker login --username jjs-dev --password ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com\necho \"${{ secrets.GCR_UPLOAD_JSON_KEY }}\" | base64 --decode | docker login --username _json_key --password-stdin gcr.io\npython3 ci-data/push_images.py\n"