name: "deploy"
on:
  push:
    branches:
      - master
      - fixup-deploy
env:
  CI: 1
  RUST_BACKTRACE: full
jobs:
  docker:
    name: docker
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: bash scripts/ci-env.sh
      - name: cargo jjs-build
        run: cargo jjs-build
        env:
          JJS_DT_DEPLOY: docker
      - name: upload docker images
        run: |
          docker login --username jjs-dev --password ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker login --username mikailbag --password ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag jjs:latest mikailbag/jjs:latest
          docker push mikailbag/jjs
          docker tag jjs:latest docker.pkg.github.com/jjs-dev/jjs/jjs:master
          docker push docker.pkg.github.com/jjs-dev/jjs/jjs:master
  deb:
    name: deb
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: Setup env
        run: bash scripts/ci-env.sh
      - name: Build debian package
        run: cargo jjs-build
        env:
          JJS_DT_DEPLOY: deb
      - name: Publish debian package artifact
        uses: actions/upload-artifact@v1
        with:
          name: jjs-amd64.deb
          path: /opt/jjs/pkg/jjs.deb
  man:
    name: man
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v1
      - name: install global dependencies
        run: |
          bash scripts/ci-env.sh
          cargo install mdbook --no-default-features
          sudo npm install -g @2fd/graphdoc
      - name: cargo jjs-build
        run: cargo jjs-build
        env:
          JJS_DT_DEPLOY: man
      - name: copy man
        run: |
          mkdir ./built-docs
          cp -r /opt/jjs/share/docs/* ./built-docs
      - name: upload man
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./built-docs
