image:
  repositoryPrefix: gcr.io/jjs-dev/
  tag: latest
  pullPolicy: Always
toolchains:
  official: true
services:
  apiserver:
    serviceType: ClusterIP
networkPolicy:
  enabled: true
dev:
  kubeScore: false