image:
  repositoryPrefix: gcr.io/jjs-dev/
  tag: latest
  pullPolicy: Always
toolchains:
  official: true
extras:
  ejui:
    enabled: true
    image: docker.pkg.github.com/sleirsgoevy/ejui/ejui:master
services:
  apiserver:
    serviceType: ClusterIP
networkPolicy:
  enabled: true
dev:
  kubeScore: false
